### PR TITLE
Fix "widge" typo

### PR DESCRIPTION
**Pull request by CodingItWrong**
🙃

### CODE REVIEW

**Comment by iamvery** [comment]
Nice! I saw this the other day and promptly forgot :laughing:

**Comment by iamvery** [comment]
Curious, did you use the "edit page" feature on the site or come here and find it yourself?

**Comment by CodingItWrong** [comment]
Found myself. I did an edit when I first started at BNR too; I might have used "edit page" back then. I forget.

**Comment by iamvery** [comment]
:+1: just curious if that works decently

**Pull request merged**
